name: Deploy MathJax Site

on:
  push:
    branches: ["main"] # Or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install mathjax-full jsdom cheerio tailwindcss@3

      - name: Create Distribution Directory
        run: mkdir dist

      - name: Render Equations to SVGs
        run: node tex_to_svg.mjs

      - name: Write Tailwind Styles
        run: npx tailwindcss -i ./src/styles.css -o ./dist/styles.css

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This points to the folder where your rendered HTML is saved
          path: './dist' 
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4